// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.DigitalInput;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Climb extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private DigitalInput lefthandLimitSwitch;
private DigitalInput leftElbowLimitSwitch;
private DigitalInput leftShoulderLimitSwitch;
private DigitalInput rightHandLimitSwitch;
private DigitalInput rightElbowLimitSwitch;
private DigitalInput rightShoulderLimitSwitch;
private WPI_TalonFX leftShoulder;
private WPI_TalonSRX leftElbow;
private WPI_TalonFX rightShoulder;
private WPI_TalonFX rightElbow;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Climb() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
lefthandLimitSwitch = new DigitalInput(2);
 addChild("lefthandLimitSwitch", lefthandLimitSwitch);
 

leftElbowLimitSwitch = new DigitalInput(3);
 addChild("LeftElbowLimitSwitch", leftElbowLimitSwitch);
 

leftShoulderLimitSwitch = new DigitalInput(4);
 addChild("LeftShoulderLimitSwitch", leftShoulderLimitSwitch);
 

rightHandLimitSwitch = new DigitalInput(5);
 addChild("RightHandLimitSwitch", rightHandLimitSwitch);
 

rightElbowLimitSwitch = new DigitalInput(6);
 addChild("RightElbowLimitSwitch", rightElbowLimitSwitch);
 

rightShoulderLimitSwitch = new DigitalInput(7);
 addChild("RightShoulderLimitSwitch", rightShoulderLimitSwitch);
 

leftShoulder = new WPI_TalonFX(7);
 
 

leftElbow = new WPI_TalonSRX(8);
 
 

rightShoulder = new WPI_TalonFX(9);
 
 

rightElbow = new WPI_TalonFX(10);
 
 


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

