// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: SequentialCommandGroup.

package frc.robot.commands;
import edu.wpi.first.wpilibj2.command.SequentialCommandGroup;
import frc.robot.RobotContainer;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.BallAcquisition;
import frc.robot.subsystems.BallIndexer;
import frc.robot.subsystems.BallShooter;
import frc.robot.subsystems.Drive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class AutoRedRight extends SequentialCommandGroup {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

    public AutoRedRight(BallAcquisition m_ballAcquisition, BallIndexer m_ballIndexer, BallShooter m_ballShooter, Drive m_Drive){

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    addCommands(
        // Add Commands here:
        // Also add parallel commands using the
        //
        // addCommands(
        //      new command1(argsN, subsystem),
        //      parallel(
        //          new command2(argsN, subsystem),
        //          new command3(argsN, subsystem)
        //      )    
        //  );
        new driveForward(7.8, RobotContainer.getInstance().m_drive),
        new DeployAcquisitionAuto(m_ballAcquisition).withTimeout(5),
        new AcquireAuto(m_ballAcquisition).withTimeout(5),
        new RetractAcquisitionAuto(m_ballAcquisition).withTimeout(5),
        new turn(-218, RobotContainer.getInstance().m_drive),
        new driveForward(11.18, RobotContainer.getInstance().m_drive),
        new DeployAcquisitionAuto(m_ballAcquisition).withTimeout(5),
        new AcquireAuto(m_ballAcquisition).withTimeout(5),
        new RetractAcquisitionAuto(m_ballAcquisition).withTimeout(5),
        new turn(-29, RobotContainer.getInstance().m_drive),
        new driveForward(6.4, RobotContainer.getInstance().m_drive),
        new ShootAuto(m_ballShooter).withTimeout(5)
        );
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
    }
}
