// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
// ROBOTBUILDER TYPE: Command.

package frc.robot.commands;
=======
package frc.robot.commands;

import org.opencv.core.Mat;

>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java
import edu.wpi.first.wpilibj2.command.CommandBase;
import frc.robot.subsystems.BallAcquisition;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import frc.robot.subsystems.BallIndexer;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS

/**
 *
 */
public class runIndexer extends CommandBase {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
        private final BallIndexer m_ballIndexer;
 
=======
    private final Drive m_drive;

>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java

    public runIndexer(BallIndexer subsystem) {
=======
    public turn2LimeLight(Drive subsystem) {
>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

        m_ballIndexer = subsystem;
        addRequirements(m_ballIndexer);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
=======

>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
=======
        LimelightUtility.EnableDriverCamera(false);
        LimelightUtility.WriteDouble("ledMode", 3); // 3 = Limelight On
>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
        m_ballIndexer.startIndexer(0.5);
=======
        LimelightUtility.RefreshTrackingData();

        if (LimelightUtility.ValidTargetFound()) {
            m_drive.JoystickDrive(RobotContainer.getInstance().getoperatorOne(),
                    LimelightUtility.TargetHorizontalOffset / 27.0);
        }
>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java
    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
       m_ballIndexer.stopIndexer();
    }


    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
        return m_ballIndexer.sensorTripped();

=======
        return true;
>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java
    }

    @Override
    public boolean runsWhenDisabled() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
        return false;

<<<<<<< HEAD:src/main/java/frc/robot/commands/runIndexer.java
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED
=======
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DISABLED

>>>>>>> 63793b70e2bf421a62065e30993cc1da7c7cbb01:src/main/java/frc/robot/commands/turn2LimeLight.java
    }
}
